#!/usr/bin/env python3

import sys

from argparse import ArgumentParser, FileType

from Bio import SeqIO


def writeboth(records, fasta, qual):
    for r in records:
        print(r.format('fasta'), file=fasta)
        print(r.format('qual'),  file=qual)


def main(args=None):
    if args is None:
        args = sys.argv[1:]

    parser = ArgumentParser(description='split a fastq file in to FASTA (stdout) and QUAL files (stderr)')
    parser.add_argument('input', metavar='FASTQ', nargs='?', type=FileType('r'), default=sys.stdin)
    parser.add_argument('fasta', metavar='FASTA', nargs='?', type=FileType('w'), default=sys.stdout)
    parser.add_argument('qual',  metavar='QUAL',  nargs='?', type=FileType('w'), default=sys.stderr)

    ns = parser.parse_args(args)

    writeboth(SeqIO.parse(ns.input, 'fastq'), ns.fasta, ns.qual)

    return 0


if __name__ == '__main__':
    sys.exit(main())
