#!/usr/bin/env python3

import signal, sys

from argparse import ArgumentParser, FileType
from re import compile as re_compile, sub as re_sub

from Bio import SeqIO
from Bio.Seq import Seq


re_ungap = re_compile(r'N')


def ungap(seqs):
    for s in seqs:
        newseq = Seq(re_sub(re_ungap, '-', str(s.seq)), s.seq.alphabet)
        s.seq = newseq
        yield s


def main(args=None):
    if args is None:
        args = sys.argv[1:]

    try:
        signal.signal(signal.SIGPIPE, signal.SIG_DFL)
    except ValueError:
        pass

    parser = ArgumentParser(description='return codon-internal Ns back to gaps (-)')
    parser.add_argument('input',  nargs='?', type=FileType('r'), default=sys.stdin)
    parser.add_argument('output', nargs='?', type=FileType('w'), default=sys.stdout)

    ns = parser.parse_args(args)

    SeqIO.write(ungap(SeqIO.parse(ns.input, 'fasta')), ns.output, 'fasta')

    return 0


if __name__ == '__main__':
    sys.exit(main())
