#!/usr/bin/env python3

import signal, sys

from argparse import ArgumentParser, FileType

from Bio import SeqIO


def rename(seqrecords, prefix, refname):
    i = 1
    for sr in seqrecords:
        if sr.id == refname:
            yield sr
        else:
            newid = prefix + '_%d' % i
            i += 1
            sr.id = newid
            sr.name = newid
            sr.description = newid
            yield sr


def main(args=None):
    if args is None:
        args = sys.argv[1:]

    try:
        signal.signal(signal.SIGPIPE, signal.SIG_DFL)
    except ValueError:
        pass

    parser = ArgumentParser(description='reorder alignment based on starting positions')
    parser.add_argument('--refname', '-r',   type=str,           default='reference')
    parser.add_argument('prefix',            type=str)
    parser.add_argument('input',  nargs='?', type=FileType('r'), default=sys.stdin)
    parser.add_argument('output', nargs='?', type=FileType('w'), default=sys.stdout)

    ns = parser.parse_args(args)

    SeqIO.write(rename(SeqIO.parse(ns.input, 'fasta'), ns.prefix, ns.refname), ns.output, 'fasta')

    return 0


if __name__ == '__main__':
    sys.exit(main())
