#!/usr/bin/env python3

import signal, sys

from argparse import ArgumentParser, FileType

from Bio import SeqIO


def label(seqs):
    for i, s in enumerate(seqs):
        newid = s.id + '_%d' % i
        desc = s.description.split(' ')
        if desc[0] == s.id:
            desc[0] = newid
            s.description = ' '.join(desc)
        s.id = newid
        s.name = newid
        yield s


def main(args=None):
    if args is None:
        args = sys.argv[1:]

    try:
        signal.signal(signal.SIGPIPE, signal.SIG_DFL)
    except ValueError:
        pass

    parser = ArgumentParser(description='append an increment variable to FASTA sequence ids')
    parser.add_argument('input',  nargs='?', type=FileType('r'), default=sys.stdin)
    parser.add_argument('output', nargs='?', type=FileType('w'), default=sys.stdout)

    ns = parser.parse_args(args)

    SeqIO.write(label(SeqIO.parse(ns.input, 'fasta')), ns.output, 'fasta')

    return 0


if __name__ == '__main__':
    sys.exit(main())
